#!/usr/bin/env bash
#nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
cp /var/www/html/index.html /var/www/html/index.html.bckp
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
