#!/usr/bin/env bash
#This script displays The content of the current directory
#In a list format. only the part of the name is shown.

for file in *
    do
    if [[ ! $file =~ ^\. ]]
    then
    nm=$(echo "$file" | cut -d'-' -f2-)
    echo "$nm"
    fi
done


