#!/usr/bin/env bash
#This script configures a server with:
#localhost resolves to 127.0.02
#facebook.com resolves to 8.8.8.8

local_host="127.0.0.2"
facebook="8.8.8.8"

echo "$local_host localhost" >> /etc/hosts
echo "$facebook facebook.com" >> /etc/hosts
