#!/usr/bin/env bash
#ssh config

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    GSSAPIAuthentication yes
    GSSAPIAuthentication yes
    SendEnv LANG LC_*
    HashKnownHosts yes
